language: dart
before_install:
- openssl aes-256-cbc -K $encrypted_aace0a50980c_key -iv $encrypted_aace0a50980c_iv
  -in ./keys/credentials.tar.gz.enc -out ./keys/credentials.tar.gz -d
before_script: pub run build_runner build
dart_task:
- dartanalyzer
- dartfmt
- test
deploy:
  provider: gae
  keyfile: "./keys/travis-service-account.json"
  project: puyopuyo
  skip_cleanup: true
