language: dart
before_install:
  - openssl aes-256-cbc -K $encrypted_1fd5fa7dcbce_key -iv $encrypted_1fd5fa7dcbce_iv
    -in ./keys/travis-service-account.json.enc -out ./keys/travis-service-account.json -d
before_script: pub run build_runner build
dart_task:
  - dartanalyzer
  - dartfmt
  - test
deploy:
  provider: gae
  keyfile: "./keys/travis-service-account.json"
  project: puyopuyo
  skip_cleanup: true
