name: puyo

dependencies:
  appengine:
  built_collection:
  built_value:
  shelf:
  shelf_static:

dev_dependencies:
  build_runner:
  built_value_generator:
  build_web_compilers:
  pedantic:
  test:
