name: puyo

dependencies:
  appengine:
  built_collection:
  built_value:
  shelf:
  shelf_static:
  shelf_web_socket:

dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:
  built_value_generator:
  pedantic:
  test:
